//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.19 at 06:17:00 PM CEST 
//


package com.sap.dpre.entities.jaxb.riskcolumnresult;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ColumnId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="Risk" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "columnId",
    "risk"
})
@XmlRootElement(name = "Column")
public class Column {

    @XmlElement(name = "ColumnId")
    protected long columnId;
    @XmlElement(name = "Risk")
    protected float risk;

    /**
     * Gets the value of the columnId property.
     * 
     */
    public long getColumnId() {
        return columnId;
    }

    /**
     * Sets the value of the columnId property.
     * 
     */
    public void setColumnId(long value) {
        this.columnId = value;
    }

    /**
     * Gets the value of the risk property.
     * 
     */
    public float getRisk() {
        return risk;
    }

    /**
     * Sets the value of the risk property.
     * 
     */
    public void setRisk(float value) {
        this.risk = value;
    }

}
